### ISSUE TITLE
Superagent dependency

### ISSUE THREAD

**Issue by jonatanklosko** [koenpunt/superagent-use#2]
Making this dependent on superagent makes it troublesome when updates come. I think it could be easily fixed by doing:

``` javascript
module.exports = function(_superagent) {
  // stuff
  return superagent;
};
```

And using it would be as follows:

``` javascript
const superagent = require('superagent');
superagent = require('superagent-use')(superagent);
```

This removes superagent dependency and just extends the user's one.
Is this repo alive? If so I can submit PR for this =)

**Comment by koenpunt** [comment]
Yeah I thought of that before, but didn't care to change it just yet. PR is welcome though :)
